go_import_path: github.com/jung-kurt/gofpdf
language: go
sudo: false
os:
  - linux
  # OSX builds are slow, reenable when faster
  # - osx
go:
  - 1.7.x
  - 1.8.x
  - tip
script: go test -v
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
notifications:
  email: false
